version: '3.7'

services:
  database:
    image: postgres:12-alpine
    container_name: challengergo
    restart: always
    volumes:
      - .pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=challengergo
      - POSTGRES_DB=challengergo
    ports:
      - "5432:5432"
    expose:
      - 5432